os: Visual Studio 2015

platform: x64

environment:
        matrix:
        - test_moar: '2019.11'
        - test_moar: '' #latest

install:
  # Install rakudostar for faster CI builds.
  - choco install rakudostar
  # Change to build folder
  - cd %APPVEYOR_BUILD_FOLDER%
  # Refresh environment variables so zef works
  - refreshenv

build: off

test_script:
  -  prove -ve "raku -I."
  - zef install .

shallow_clone: true
